import streamlit as st
import pandas as pd
import numpy as np
import joblib


# ==========================
# Load Model Files
# ==========================

model = joblib.load("heart_model.pkl")
scaler = joblib.load("scaler.pkl")
feature_names = joblib.load("feature_names.pkl")


# ==========================
# Page Settings
# ==========================

st.set_page_config(
    page_title="Heart Disease Prediction System",
    page_icon="🫀",
    layout="centered"
)


# ==========================
# Title
# ==========================

st.title("🫀 Heart Disease Prediction System")

st.write(
    "Enter patient medical details to predict the likelihood of heart disease."
)

st.markdown("---")


# ==========================
# Inputs
# ==========================

st.header("Patient Details")


age = st.number_input(
    "Age",
    1,
    120,
    50
)


sex = st.selectbox(
    "Gender",
    ["Female", "Male"]
)


cp = st.selectbox(
    "Chest Pain Type",
    [
        "Typical Angina",
        "Atypical Angina",
        "Non-anginal Pain",
        "Asymptomatic"
    ]
)


trestbps = st.number_input(
    "Resting Blood Pressure",
    80,
    250,
    120
)


chol = st.number_input(
    "Cholesterol",
    100,
    600,
    200
)


fbs = st.selectbox(
    "Fasting Blood Sugar > 120 mg/dL",
    ["No", "Yes"]
)


restecg = st.selectbox(
    "Resting ECG",
    [
        "Normal",
        "ST-T Wave Abnormality",
        "Left Ventricular Hypertrophy"
    ]
)


thalach = st.number_input(
    "Maximum Heart Rate Achieved",
    50,
    250,
    150
)


exang = st.selectbox(
    "Exercise Induced Angina",
    ["No", "Yes"]
)


oldpeak = st.number_input(
    "Oldpeak",
    0.0,
    10.0,
    1.0
)


slope = st.selectbox(
    "Slope",
    [
        "Upsloping",
        "Flat",
        "Downsloping"
    ]
)


ca = st.selectbox(
    "Number of Major Vessels",
    [0,1,2,3,4]
)


thal = st.selectbox(
    "Thalassemia",
    [0,1,2,3]
)



# ==========================
# Prediction
# ==========================

if st.button("Predict"):


    # Create input dataframe
    input_data = pd.DataFrame(
        np.zeros((1, len(feature_names))),
        columns=feature_names
    )


    # Numerical values
    input_data["age"] = age
    input_data["trestbps"] = trestbps
    input_data["chol"] = chol
    input_data["thalach"] = thalach
    input_data["oldpeak"] = oldpeak



    # Encoding

    input_data["sex"] = 1 if sex=="Male" else 0

    cp_map = {
        "Typical Angina":0,
        "Atypical Angina":1,
        "Non-anginal Pain":2,
        "Asymptomatic":3
    }

    input_data["cp"] = cp_map[cp]


    input_data["fbs"] = 1 if fbs=="Yes" else 0


    restecg_map = {
        "Normal":0,
        "ST-T Wave Abnormality":1,
        "Left Ventricular Hypertrophy":2
    }

    input_data["restecg"] = restecg_map[restecg]


    input_data["exang"] = 1 if exang=="Yes" else 0


    slope_map = {
        "Upsloping":0,
        "Flat":1,
        "Downsloping":2
    }

    input_data["slope"] = slope_map[slope]


    input_data["ca"] = ca
    input_data["thal"] = thal



    # Scaling

    input_data = scaler.transform(input_data)



    # Prediction

    prediction = model.predict(input_data)[0]

    probability = model.predict_proba(input_data)[0]



    st.markdown("---")


    if prediction == 1:

        st.error("❤️ Prediction: Heart Disease")

        confidence = probability[1]*100

    else:

        st.success("💚 Prediction: No Heart Disease")

        confidence = probability[0]*100



    st.write(
        f"### Confidence: {confidence:.2f}%"
    )


    # Risk Level

    risk_score = 0


    if age >= 60:
        risk_score += 1

    if trestbps >= 140:
        risk_score += 1

    if chol >= 240:
        risk_score += 1

    if fbs=="Yes":
        risk_score += 1

    if exang=="Yes":
        risk_score += 1

    if oldpeak >=2:
        risk_score += 1

    if ca>=2:
        risk_score +=1


    if prediction==1:
        risk_score +=2



    if risk_score <=2:
        risk="🟢 Low Risk"

    elif risk_score<=5:
        risk="🟡 Medium Risk"

    else:
        risk="🔴 High Risk"


    st.write(
        f"### Risk Level: {risk}"
    )


    st.markdown("---")


    st.subheader("Possible Risk Factors")


    if chol>=240:
        st.write("🫀 High Cholesterol")

    if trestbps>=140:
        st.write("🩸 High Blood Pressure")

    if fbs=="Yes":
        st.write("🍬 High Blood Sugar")

    if exang=="Yes":
        st.write("🏃 Exercise Induced Angina")

    if oldpeak>=2:
        st.write("📈 High Oldpeak")


    st.markdown("---")


    st.warning(
        "⚠️ This prediction is generated by a machine learning model "
        "and is not a medical diagnosis. Consult a healthcare professional."
    )


st.caption(
    "Developed using Random Forest, SMOTE and Streamlit"
)